parameters:

  sql_backup.class:       dmSqlBackup
  sql_backup.adapters:
    mysql:                dmSqlBackupAdapterMysql
  sql_backup.options:
    backup_dir:           SF_ROOT_DIR/data/dm/backup/sql


services:

  sql_backup:
    class:                %sql_backup.class%
    shared:               false
    arguments:            [ @filesystem, %sql_backup.adapters%, %sql_backup.options% ]